apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: default
data:
  APP_NAME: "hello-world"
  APP_VERSION: "1.0.0"
  APP_ENV: "production-3"
  DB_HOST: "database-host-2"
  DB_PORT: "5432"

