apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  labels:
    app: my-app
  annotations:
    metis.configmap.reloader/match: app-config
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: app-container
          image: nginx
          ports:
            - containerPort: 80  # Changed from 8080 to match nginx default
          volumeMounts:
            - name: app-config-volume
              mountPath: /etc/app-config
      volumes:
        - name: app-config-volume
          configMap:
            name: app-config
