apiVersion: apps/v1
kind: Deployment
metadata:
  name: reloader
  namespace: reloader
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reloader
  template:
    metadata:
      labels:
        app: reloader
    spec:
      containers:
      - name: reloader
        image: stakater/reloader:latest  # (or stable version)
        ports:
        - containerPort: 8080

