apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: default
data:
  APP_NAME: "MyApp"
  APP_VERSION: "1.0.0"
  APP_ENV: "production"
  DB_HOST: "my-database-host"
  DB_PORT: "5432"

