apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  namespace: default
  annotations:
    reloader.stakater.com/auto: "true"  # Trigger reloader for the ConfigMap changes
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: nginx-container
          image: nginx:latest
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: app-config  # Referencing ConfigMap to load env vars

